parameters:
    document_storage_directory: '%kernel.project_dir%/var/documents'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Service\DocumentService:
        arguments:
            $logger: '@logger'
            $storageDirectory: '%document_storage_directory%'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
